# Generated by Django 4.2.3 on 2023-07-28 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_usuario_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='data_criacao_codigo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tempo_expiracao_codigo',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='codigo_autenticacao',
            field=models.CharField(max_length=6),
        ),
    ]
