# Generated by Django 4.2.3 on 2023-07-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_perfilusuario_data_criacao_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_criacao_codigo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
